apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-service
spec:
  type: NodePort
  selector:
    app: jenkins-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test-deployment
  labels:
    app: jenkins-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test
        image: "debian-cloud-test:8083/com.opcode.jenkins-test:latest"
        ports:
        - containerPort: 8080
